vote:
  image: phierbaba/vote:latest
  ports:
    - 5000:80
  links:
    - redis:redis

redis:
  image: redis:alpine

db:
  image: postgres:9.4

result:
  image: phierbaba/result:latest
  ports:
    - 5001:4000
  links:
    - db:db

worker:
  image: phierbaba/worker:latest
  links:
    - redis:redis
    - db:db